/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as AboutMidasbuyIndexRouteImport } from './routes/about-midasbuy/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as BgmiIndexRouteImport } from './routes/bgmi/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as CarPurchaseIndexRouteImport } from './routes/car-purchase/index'
import { Route as CareersIndexRouteImport } from './routes/careers/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as CookiePolicyIndexRouteImport } from './routes/cookie-policy/index'
import { Route as CopyrightNoticeIndexRouteImport } from './routes/copyright-notice/index'
import { Route as CountriesIndexRouteImport } from './routes/countries/index'
import { Route as CouponsIndexRouteImport } from './routes/coupons/index'
import { Route as CustomerReviewsIndexRouteImport } from './routes/customer-reviews/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as FaqsIndexRouteImport } from './routes/faqs/index'
import { Route as FreeFireIndexRouteImport } from './routes/free-fire/index'
import { Route as GamingShopIndexRouteImport } from './routes/gaming-shop/index'
import { Route as HelpCenterIndexRouteImport } from './routes/help-center/index'
import { Route as HonorOfKingsIndexRouteImport } from './routes/honor-of-kings/index'
import { Route as IpDetectorIndexRouteImport } from './routes/ip-detector/index'
import { Route as MyFeedbacksIndexRouteImport } from './routes/my-feedbacks/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as OrderCancelledIndexRouteImport } from './routes/order-cancelled/index'
import { Route as OrderCenterIndexRouteImport } from './routes/order-center/index'
import { Route as PartnersIndexRouteImport } from './routes/partners/index'
import { Route as PaymentCanceledIndexRouteImport } from './routes/payment-canceled/index'
import { Route as PaymentIssuesIndexRouteImport } from './routes/payment-issues/index'
import { Route as PlayerIdIndexRouteImport } from './routes/player-id/index'
import { Route as PressIndexRouteImport } from './routes/press/index'
import { Route as PrivacyPolicyIndexRouteImport } from './routes/privacy-policy/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PubgAccountsIndexRouteImport } from './routes/pubg-accounts/index'
import { Route as PubgMobileIndexRouteImport } from './routes/pubg-mobile/index'
import { Route as PurchaseHistoryIndexRouteImport } from './routes/purchase-history/index'
import { Route as RedeemIndexRouteImport } from './routes/redeem/index'
import { Route as RefundPolicyIndexRouteImport } from './routes/refund-policy/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as RobloxIndexRouteImport } from './routes/roblox/index'
import { Route as SecurityIndexRouteImport } from './routes/security/index'
import { Route as TermsOfServiceIndexRouteImport } from './routes/terms-of-service/index'
import { Route as ThankYouIndexRouteImport } from './routes/thank-you/index'
import { Route as ThankyouIndexRouteImport } from './routes/thankyou/index'
import { Route as TrackOrdersIndexRouteImport } from './routes/track-orders/index'
import { Route as ValorantIndexRouteImport } from './routes/valorant/index'
import { Route as AuthCallbackIndexRouteImport } from './routes/auth/callback/index'
import { Route as BlogSlugIndexRouteImport } from './routes/blog/$slug/index'
import { Route as CheckoutIdIndexRouteImport } from './routes/checkout/$id/index'
import { Route as MidasbuyCountryCodeIndexRouteImport } from './routes/midasbuy/$countryCode/index'
import { Route as PayCardIndexRouteImport } from './routes/pay/card/index'
import { Route as PaymentFailedIndexRouteImport } from './routes/payment/failed/index'
import { Route as PaymentPayproReturnIndexRouteImport } from './routes/payment/paypro-return/index'
import { Route as PaymentSuccessIndexRouteImport } from './routes/payment/success/index'
import { Route as PurchaseIdIndexRouteImport } from './routes/purchase/$id/index'
import { Route as ShopVideosIndexRouteImport } from './routes/shop/videos/index'
import { Route as CheckoutFreeFireIdIndexRouteImport } from './routes/checkout/free-fire/$id/index'
import { Route as HonorOfKingsPurchaseIdIndexRouteImport } from './routes/honor-of-kings/purchase/$id/index'
import { Route as MidasbuyBuyFreefireIndexRouteImport } from './routes/midasbuy/buy/freefire/index'
import { Route as MidasbuyBuyPubgmIndexRouteImport } from './routes/midasbuy/buy/pubgm/index'
import { Route as PubgAccountsCheckoutIdIndexRouteImport } from './routes/pubg-accounts/checkout/$id/index'
import { Route as PurchaseFreeFireIdIndexRouteImport } from './routes/purchase/free-fire/$id/index'
import { Route as RobloxCheckoutIdIndexRouteImport } from './routes/roblox/checkout/$id/index'
import { Route as RobloxPurchaseIdIndexRouteImport } from './routes/roblox/purchase/$id/index'
import { Route as ValorantCheckoutIdIndexRouteImport } from './routes/valorant/checkout/$id/index'
import { Route as ValorantPurchaseIdIndexRouteImport } from './routes/valorant/purchase/$id/index'
import { Route as ApiAuthCallbackGoogleIndexRouteImport } from './routes/api/auth/callback/google/index'
import { Route as MidasbuyCountryCodeBuyBgmiIndexRouteImport } from './routes/midasbuy/$countryCode/buy/bgmi/index'
import { Route as MidasbuyCountryCodeBuyCarIndexRouteImport } from './routes/midasbuy/$countryCode/buy/car/index'
import { Route as MidasbuyCountryCodeBuyFreefireIndexRouteImport } from './routes/midasbuy/$countryCode/buy/freefire/index'
import { Route as MidasbuyCountryCodeBuyHonorofkingsIndexRouteImport } from './routes/midasbuy/$countryCode/buy/honorofkings/index'
import { Route as MidasbuyCountryCodeBuyPubgmIndexRouteImport } from './routes/midasbuy/$countryCode/buy/pubgm/index'
import { Route as MidasbuyCountryCodeBuyRobloxIndexRouteImport } from './routes/midasbuy/$countryCode/buy/roblox/index'
import { Route as MidasbuyCountryCodeBuyValorantIndexRouteImport } from './routes/midasbuy/$countryCode/buy/valorant/index'
import { Route as MidasbuyCountryCodeGameArenabreakoutIndexRouteImport } from './routes/midasbuy/$countryCode/game/arenabreakout/index'
import { Route as MidasbuyCountryCodeGameDeltaforceIndexRouteImport } from './routes/midasbuy/$countryCode/game/deltaforce/index'
import { Route as MidasbuyCountryCodeGameDragonheirIndexRouteImport } from './routes/midasbuy/$countryCode/game/dragonheir/index'
import { Route as MidasbuyCountryCodeGameHonorofkingsIndexRouteImport } from './routes/midasbuy/$countryCode/game/honorofkings/index'
import { Route as MidasbuyCountryCodeGameLudoIndexRouteImport } from './routes/midasbuy/$countryCode/game/ludo/index'
import { Route as MidasbuyCountryCodeGameNbaIndexRouteImport } from './routes/midasbuy/$countryCode/game/nba/index'
import { Route as MidasbuyCountryCodeGameUndawnIndexRouteImport } from './routes/midasbuy/$countryCode/game/undawn/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMidasbuyIndexRoute = AboutMidasbuyIndexRouteImport.update({
  id: '/about-midasbuy/',
  path: '/about-midasbuy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const BgmiIndexRoute = BgmiIndexRouteImport.update({
  id: '/bgmi/',
  path: '/bgmi/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarPurchaseIndexRoute = CarPurchaseIndexRouteImport.update({
  id: '/car-purchase/',
  path: '/car-purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/careers/',
  path: '/careers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyIndexRoute = CookiePolicyIndexRouteImport.update({
  id: '/cookie-policy/',
  path: '/cookie-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyrightNoticeIndexRoute = CopyrightNoticeIndexRouteImport.update({
  id: '/copyright-notice/',
  path: '/copyright-notice/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsIndexRoute = CouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerReviewsIndexRoute = CustomerReviewsIndexRouteImport.update({
  id: '/customer-reviews/',
  path: '/customer-reviews/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsIndexRoute = FaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeFireIndexRoute = FreeFireIndexRouteImport.update({
  id: '/free-fire/',
  path: '/free-fire/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingShopIndexRoute = GamingShopIndexRouteImport.update({
  id: '/gaming-shop/',
  path: '/gaming-shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCenterIndexRoute = HelpCenterIndexRouteImport.update({
  id: '/help-center/',
  path: '/help-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorOfKingsIndexRoute = HonorOfKingsIndexRouteImport.update({
  id: '/honor-of-kings/',
  path: '/honor-of-kings/',
  getParentRoute: () => rootRouteImport,
} as any)
const IpDetectorIndexRoute = IpDetectorIndexRouteImport.update({
  id: '/ip-detector/',
  path: '/ip-detector/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFeedbacksIndexRoute = MyFeedbacksIndexRouteImport.update({
  id: '/my-feedbacks/',
  path: '/my-feedbacks/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCancelledIndexRoute = OrderCancelledIndexRouteImport.update({
  id: '/order-cancelled/',
  path: '/order-cancelled/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderCenterIndexRoute = OrderCenterIndexRouteImport.update({
  id: '/order-center/',
  path: '/order-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCanceledIndexRoute = PaymentCanceledIndexRouteImport.update({
  id: '/payment-canceled/',
  path: '/payment-canceled/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentIssuesIndexRoute = PaymentIssuesIndexRouteImport.update({
  id: '/payment-issues/',
  path: '/payment-issues/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdIndexRoute = PlayerIdIndexRouteImport.update({
  id: '/player-id/',
  path: '/player-id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PressIndexRoute = PressIndexRouteImport.update({
  id: '/press/',
  path: '/press/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyIndexRoute = PrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubgAccountsIndexRoute = PubgAccountsIndexRouteImport.update({
  id: '/pubg-accounts/',
  path: '/pubg-accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubgMobileIndexRoute = PubgMobileIndexRouteImport.update({
  id: '/pubg-mobile/',
  path: '/pubg-mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseHistoryIndexRoute = PurchaseHistoryIndexRouteImport.update({
  id: '/purchase-history/',
  path: '/purchase-history/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemIndexRoute = RedeemIndexRouteImport.update({
  id: '/redeem/',
  path: '/redeem/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyIndexRoute = RefundPolicyIndexRouteImport.update({
  id: '/refund-policy/',
  path: '/refund-policy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxIndexRoute = RobloxIndexRouteImport.update({
  id: '/roblox/',
  path: '/roblox/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityIndexRoute = SecurityIndexRouteImport.update({
  id: '/security/',
  path: '/security/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceIndexRoute = TermsOfServiceIndexRouteImport.update({
  id: '/terms-of-service/',
  path: '/terms-of-service/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouIndexRoute = ThankYouIndexRouteImport.update({
  id: '/thank-you/',
  path: '/thank-you/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankyouIndexRoute = ThankyouIndexRouteImport.update({
  id: '/thankyou/',
  path: '/thankyou/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrdersIndexRoute = TrackOrdersIndexRouteImport.update({
  id: '/track-orders/',
  path: '/track-orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorantIndexRoute = ValorantIndexRouteImport.update({
  id: '/valorant/',
  path: '/valorant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackIndexRoute = AuthCallbackIndexRouteImport.update({
  id: '/auth/callback/',
  path: '/auth/callback/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugIndexRoute = BlogSlugIndexRouteImport.update({
  id: '/blog/$slug/',
  path: '/blog/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdIndexRoute = CheckoutIdIndexRouteImport.update({
  id: '/checkout/$id/',
  path: '/checkout/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const MidasbuyCountryCodeIndexRoute =
  MidasbuyCountryCodeIndexRouteImport.update({
    id: '/midasbuy/$countryCode/',
    path: '/midasbuy/$countryCode/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PayCardIndexRoute = PayCardIndexRouteImport.update({
  id: '/pay/card/',
  path: '/pay/card/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedIndexRoute = PaymentFailedIndexRouteImport.update({
  id: '/payment/failed/',
  path: '/payment/failed/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentPayproReturnIndexRoute =
  PaymentPayproReturnIndexRouteImport.update({
    id: '/payment/paypro-return/',
    path: '/payment/paypro-return/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PaymentSuccessIndexRoute = PaymentSuccessIndexRouteImport.update({
  id: '/payment/success/',
  path: '/payment/success/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIdIndexRoute = PurchaseIdIndexRouteImport.update({
  id: '/purchase/$id/',
  path: '/purchase/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopVideosIndexRoute = ShopVideosIndexRouteImport.update({
  id: '/shop/videos/',
  path: '/shop/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutFreeFireIdIndexRoute = CheckoutFreeFireIdIndexRouteImport.update({
  id: '/checkout/free-fire/$id/',
  path: '/checkout/free-fire/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const HonorOfKingsPurchaseIdIndexRoute =
  HonorOfKingsPurchaseIdIndexRouteImport.update({
    id: '/honor-of-kings/purchase/$id/',
    path: '/honor-of-kings/purchase/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyBuyFreefireIndexRoute =
  MidasbuyBuyFreefireIndexRouteImport.update({
    id: '/midasbuy/buy/freefire/',
    path: '/midasbuy/buy/freefire/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyBuyPubgmIndexRoute = MidasbuyBuyPubgmIndexRouteImport.update({
  id: '/midasbuy/buy/pubgm/',
  path: '/midasbuy/buy/pubgm/',
  getParentRoute: () => rootRouteImport,
} as any)
const PubgAccountsCheckoutIdIndexRoute =
  PubgAccountsCheckoutIdIndexRouteImport.update({
    id: '/pubg-accounts/checkout/$id/',
    path: '/pubg-accounts/checkout/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PurchaseFreeFireIdIndexRoute = PurchaseFreeFireIdIndexRouteImport.update({
  id: '/purchase/free-fire/$id/',
  path: '/purchase/free-fire/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxCheckoutIdIndexRoute = RobloxCheckoutIdIndexRouteImport.update({
  id: '/roblox/checkout/$id/',
  path: '/roblox/checkout/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RobloxPurchaseIdIndexRoute = RobloxPurchaseIdIndexRouteImport.update({
  id: '/roblox/purchase/$id/',
  path: '/roblox/purchase/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorantCheckoutIdIndexRoute = ValorantCheckoutIdIndexRouteImport.update({
  id: '/valorant/checkout/$id/',
  path: '/valorant/checkout/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorantPurchaseIdIndexRoute = ValorantPurchaseIdIndexRouteImport.update({
  id: '/valorant/purchase/$id/',
  path: '/valorant/purchase/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleIndexRoute =
  ApiAuthCallbackGoogleIndexRouteImport.update({
    id: '/api/auth/callback/google/',
    path: '/api/auth/callback/google/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyBgmiIndexRoute =
  MidasbuyCountryCodeBuyBgmiIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/bgmi/',
    path: '/midasbuy/$countryCode/buy/bgmi/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyCarIndexRoute =
  MidasbuyCountryCodeBuyCarIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/car/',
    path: '/midasbuy/$countryCode/buy/car/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyFreefireIndexRoute =
  MidasbuyCountryCodeBuyFreefireIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/freefire/',
    path: '/midasbuy/$countryCode/buy/freefire/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyHonorofkingsIndexRoute =
  MidasbuyCountryCodeBuyHonorofkingsIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/honorofkings/',
    path: '/midasbuy/$countryCode/buy/honorofkings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyPubgmIndexRoute =
  MidasbuyCountryCodeBuyPubgmIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/pubgm/',
    path: '/midasbuy/$countryCode/buy/pubgm/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyRobloxIndexRoute =
  MidasbuyCountryCodeBuyRobloxIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/roblox/',
    path: '/midasbuy/$countryCode/buy/roblox/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeBuyValorantIndexRoute =
  MidasbuyCountryCodeBuyValorantIndexRouteImport.update({
    id: '/midasbuy/$countryCode/buy/valorant/',
    path: '/midasbuy/$countryCode/buy/valorant/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameArenabreakoutIndexRoute =
  MidasbuyCountryCodeGameArenabreakoutIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/arenabreakout/',
    path: '/midasbuy/$countryCode/game/arenabreakout/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameDeltaforceIndexRoute =
  MidasbuyCountryCodeGameDeltaforceIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/deltaforce/',
    path: '/midasbuy/$countryCode/game/deltaforce/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameDragonheirIndexRoute =
  MidasbuyCountryCodeGameDragonheirIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/dragonheir/',
    path: '/midasbuy/$countryCode/game/dragonheir/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameHonorofkingsIndexRoute =
  MidasbuyCountryCodeGameHonorofkingsIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/honorofkings/',
    path: '/midasbuy/$countryCode/game/honorofkings/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameLudoIndexRoute =
  MidasbuyCountryCodeGameLudoIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/ludo/',
    path: '/midasbuy/$countryCode/game/ludo/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameNbaIndexRoute =
  MidasbuyCountryCodeGameNbaIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/nba/',
    path: '/midasbuy/$countryCode/game/nba/',
    getParentRoute: () => rootRouteImport,
  } as any)
const MidasbuyCountryCodeGameUndawnIndexRoute =
  MidasbuyCountryCodeGameUndawnIndexRouteImport.update({
    id: '/midasbuy/$countryCode/game/undawn/',
    path: '/midasbuy/$countryCode/game/undawn/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/about-midasbuy/': typeof AboutMidasbuyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/bgmi/': typeof BgmiIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/car-purchase/': typeof CarPurchaseIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/cookie-policy/': typeof CookiePolicyIndexRoute
  '/copyright-notice/': typeof CopyrightNoticeIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/coupons/': typeof CouponsIndexRoute
  '/customer-reviews/': typeof CustomerReviewsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/free-fire/': typeof FreeFireIndexRoute
  '/gaming-shop/': typeof GamingShopIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/honor-of-kings/': typeof HonorOfKingsIndexRoute
  '/ip-detector/': typeof IpDetectorIndexRoute
  '/my-feedbacks/': typeof MyFeedbacksIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/order-cancelled/': typeof OrderCancelledIndexRoute
  '/order-center/': typeof OrderCenterIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/payment-canceled/': typeof PaymentCanceledIndexRoute
  '/payment-issues/': typeof PaymentIssuesIndexRoute
  '/player-id/': typeof PlayerIdIndexRoute
  '/press/': typeof PressIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/pubg-accounts/': typeof PubgAccountsIndexRoute
  '/pubg-mobile/': typeof PubgMobileIndexRoute
  '/purchase-history/': typeof PurchaseHistoryIndexRoute
  '/redeem/': typeof RedeemIndexRoute
  '/refund-policy/': typeof RefundPolicyIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/roblox/': typeof RobloxIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/terms-of-service/': typeof TermsOfServiceIndexRoute
  '/thank-you/': typeof ThankYouIndexRoute
  '/thankyou/': typeof ThankyouIndexRoute
  '/track-orders/': typeof TrackOrdersIndexRoute
  '/valorant/': typeof ValorantIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/checkout/$id/': typeof CheckoutIdIndexRoute
  '/midasbuy/$countryCode/': typeof MidasbuyCountryCodeIndexRoute
  '/pay/card/': typeof PayCardIndexRoute
  '/payment/failed/': typeof PaymentFailedIndexRoute
  '/payment/paypro-return/': typeof PaymentPayproReturnIndexRoute
  '/payment/success/': typeof PaymentSuccessIndexRoute
  '/purchase/$id/': typeof PurchaseIdIndexRoute
  '/shop/videos/': typeof ShopVideosIndexRoute
  '/checkout/free-fire/$id/': typeof CheckoutFreeFireIdIndexRoute
  '/honor-of-kings/purchase/$id/': typeof HonorOfKingsPurchaseIdIndexRoute
  '/midasbuy/buy/freefire/': typeof MidasbuyBuyFreefireIndexRoute
  '/midasbuy/buy/pubgm/': typeof MidasbuyBuyPubgmIndexRoute
  '/pubg-accounts/checkout/$id/': typeof PubgAccountsCheckoutIdIndexRoute
  '/purchase/free-fire/$id/': typeof PurchaseFreeFireIdIndexRoute
  '/roblox/checkout/$id/': typeof RobloxCheckoutIdIndexRoute
  '/roblox/purchase/$id/': typeof RobloxPurchaseIdIndexRoute
  '/valorant/checkout/$id/': typeof ValorantCheckoutIdIndexRoute
  '/valorant/purchase/$id/': typeof ValorantPurchaseIdIndexRoute
  '/api/auth/callback/google/': typeof ApiAuthCallbackGoogleIndexRoute
  '/midasbuy/$countryCode/buy/bgmi/': typeof MidasbuyCountryCodeBuyBgmiIndexRoute
  '/midasbuy/$countryCode/buy/car/': typeof MidasbuyCountryCodeBuyCarIndexRoute
  '/midasbuy/$countryCode/buy/freefire/': typeof MidasbuyCountryCodeBuyFreefireIndexRoute
  '/midasbuy/$countryCode/buy/honorofkings/': typeof MidasbuyCountryCodeBuyHonorofkingsIndexRoute
  '/midasbuy/$countryCode/buy/pubgm/': typeof MidasbuyCountryCodeBuyPubgmIndexRoute
  '/midasbuy/$countryCode/buy/roblox/': typeof MidasbuyCountryCodeBuyRobloxIndexRoute
  '/midasbuy/$countryCode/buy/valorant/': typeof MidasbuyCountryCodeBuyValorantIndexRoute
  '/midasbuy/$countryCode/game/arenabreakout/': typeof MidasbuyCountryCodeGameArenabreakoutIndexRoute
  '/midasbuy/$countryCode/game/deltaforce/': typeof MidasbuyCountryCodeGameDeltaforceIndexRoute
  '/midasbuy/$countryCode/game/dragonheir/': typeof MidasbuyCountryCodeGameDragonheirIndexRoute
  '/midasbuy/$countryCode/game/honorofkings/': typeof MidasbuyCountryCodeGameHonorofkingsIndexRoute
  '/midasbuy/$countryCode/game/ludo/': typeof MidasbuyCountryCodeGameLudoIndexRoute
  '/midasbuy/$countryCode/game/nba/': typeof MidasbuyCountryCodeGameNbaIndexRoute
  '/midasbuy/$countryCode/game/undawn/': typeof MidasbuyCountryCodeGameUndawnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/about-midasbuy': typeof AboutMidasbuyIndexRoute
  '/admin': typeof AdminIndexRoute
  '/auth': typeof AuthIndexRoute
  '/bgmi': typeof BgmiIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/car-purchase': typeof CarPurchaseIndexRoute
  '/careers': typeof CareersIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/cookie-policy': typeof CookiePolicyIndexRoute
  '/copyright-notice': typeof CopyrightNoticeIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/coupons': typeof CouponsIndexRoute
  '/customer-reviews': typeof CustomerReviewsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/faqs': typeof FaqsIndexRoute
  '/free-fire': typeof FreeFireIndexRoute
  '/gaming-shop': typeof GamingShopIndexRoute
  '/help-center': typeof HelpCenterIndexRoute
  '/honor-of-kings': typeof HonorOfKingsIndexRoute
  '/ip-detector': typeof IpDetectorIndexRoute
  '/my-feedbacks': typeof MyFeedbacksIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/order-cancelled': typeof OrderCancelledIndexRoute
  '/order-center': typeof OrderCenterIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/payment-canceled': typeof PaymentCanceledIndexRoute
  '/payment-issues': typeof PaymentIssuesIndexRoute
  '/player-id': typeof PlayerIdIndexRoute
  '/press': typeof PressIndexRoute
  '/privacy-policy': typeof PrivacyPolicyIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/pubg-accounts': typeof PubgAccountsIndexRoute
  '/pubg-mobile': typeof PubgMobileIndexRoute
  '/purchase-history': typeof PurchaseHistoryIndexRoute
  '/redeem': typeof RedeemIndexRoute
  '/refund-policy': typeof RefundPolicyIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/roblox': typeof RobloxIndexRoute
  '/security': typeof SecurityIndexRoute
  '/terms-of-service': typeof TermsOfServiceIndexRoute
  '/thank-you': typeof ThankYouIndexRoute
  '/thankyou': typeof ThankyouIndexRoute
  '/track-orders': typeof TrackOrdersIndexRoute
  '/valorant': typeof ValorantIndexRoute
  '/auth/callback': typeof AuthCallbackIndexRoute
  '/blog/$slug': typeof BlogSlugIndexRoute
  '/checkout/$id': typeof CheckoutIdIndexRoute
  '/midasbuy/$countryCode': typeof MidasbuyCountryCodeIndexRoute
  '/pay/card': typeof PayCardIndexRoute
  '/payment/failed': typeof PaymentFailedIndexRoute
  '/payment/paypro-return': typeof PaymentPayproReturnIndexRoute
  '/payment/success': typeof PaymentSuccessIndexRoute
  '/purchase/$id': typeof PurchaseIdIndexRoute
  '/shop/videos': typeof ShopVideosIndexRoute
  '/checkout/free-fire/$id': typeof CheckoutFreeFireIdIndexRoute
  '/honor-of-kings/purchase/$id': typeof HonorOfKingsPurchaseIdIndexRoute
  '/midasbuy/buy/freefire': typeof MidasbuyBuyFreefireIndexRoute
  '/midasbuy/buy/pubgm': typeof MidasbuyBuyPubgmIndexRoute
  '/pubg-accounts/checkout/$id': typeof PubgAccountsCheckoutIdIndexRoute
  '/purchase/free-fire/$id': typeof PurchaseFreeFireIdIndexRoute
  '/roblox/checkout/$id': typeof RobloxCheckoutIdIndexRoute
  '/roblox/purchase/$id': typeof RobloxPurchaseIdIndexRoute
  '/valorant/checkout/$id': typeof ValorantCheckoutIdIndexRoute
  '/valorant/purchase/$id': typeof ValorantPurchaseIdIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleIndexRoute
  '/midasbuy/$countryCode/buy/bgmi': typeof MidasbuyCountryCodeBuyBgmiIndexRoute
  '/midasbuy/$countryCode/buy/car': typeof MidasbuyCountryCodeBuyCarIndexRoute
  '/midasbuy/$countryCode/buy/freefire': typeof MidasbuyCountryCodeBuyFreefireIndexRoute
  '/midasbuy/$countryCode/buy/honorofkings': typeof MidasbuyCountryCodeBuyHonorofkingsIndexRoute
  '/midasbuy/$countryCode/buy/pubgm': typeof MidasbuyCountryCodeBuyPubgmIndexRoute
  '/midasbuy/$countryCode/buy/roblox': typeof MidasbuyCountryCodeBuyRobloxIndexRoute
  '/midasbuy/$countryCode/buy/valorant': typeof MidasbuyCountryCodeBuyValorantIndexRoute
  '/midasbuy/$countryCode/game/arenabreakout': typeof MidasbuyCountryCodeGameArenabreakoutIndexRoute
  '/midasbuy/$countryCode/game/deltaforce': typeof MidasbuyCountryCodeGameDeltaforceIndexRoute
  '/midasbuy/$countryCode/game/dragonheir': typeof MidasbuyCountryCodeGameDragonheirIndexRoute
  '/midasbuy/$countryCode/game/honorofkings': typeof MidasbuyCountryCodeGameHonorofkingsIndexRoute
  '/midasbuy/$countryCode/game/ludo': typeof MidasbuyCountryCodeGameLudoIndexRoute
  '/midasbuy/$countryCode/game/nba': typeof MidasbuyCountryCodeGameNbaIndexRoute
  '/midasbuy/$countryCode/game/undawn': typeof MidasbuyCountryCodeGameUndawnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/about-midasbuy/': typeof AboutMidasbuyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/bgmi/': typeof BgmiIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/car-purchase/': typeof CarPurchaseIndexRoute
  '/careers/': typeof CareersIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/cookie-policy/': typeof CookiePolicyIndexRoute
  '/copyright-notice/': typeof CopyrightNoticeIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/coupons/': typeof CouponsIndexRoute
  '/customer-reviews/': typeof CustomerReviewsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/faqs/': typeof FaqsIndexRoute
  '/free-fire/': typeof FreeFireIndexRoute
  '/gaming-shop/': typeof GamingShopIndexRoute
  '/help-center/': typeof HelpCenterIndexRoute
  '/honor-of-kings/': typeof HonorOfKingsIndexRoute
  '/ip-detector/': typeof IpDetectorIndexRoute
  '/my-feedbacks/': typeof MyFeedbacksIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/order-cancelled/': typeof OrderCancelledIndexRoute
  '/order-center/': typeof OrderCenterIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/payment-canceled/': typeof PaymentCanceledIndexRoute
  '/payment-issues/': typeof PaymentIssuesIndexRoute
  '/player-id/': typeof PlayerIdIndexRoute
  '/press/': typeof PressIndexRoute
  '/privacy-policy/': typeof PrivacyPolicyIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/pubg-accounts/': typeof PubgAccountsIndexRoute
  '/pubg-mobile/': typeof PubgMobileIndexRoute
  '/purchase-history/': typeof PurchaseHistoryIndexRoute
  '/redeem/': typeof RedeemIndexRoute
  '/refund-policy/': typeof RefundPolicyIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/roblox/': typeof RobloxIndexRoute
  '/security/': typeof SecurityIndexRoute
  '/terms-of-service/': typeof TermsOfServiceIndexRoute
  '/thank-you/': typeof ThankYouIndexRoute
  '/thankyou/': typeof ThankyouIndexRoute
  '/track-orders/': typeof TrackOrdersIndexRoute
  '/valorant/': typeof ValorantIndexRoute
  '/auth/callback/': typeof AuthCallbackIndexRoute
  '/blog/$slug/': typeof BlogSlugIndexRoute
  '/checkout/$id/': typeof CheckoutIdIndexRoute
  '/midasbuy/$countryCode/': typeof MidasbuyCountryCodeIndexRoute
  '/pay/card/': typeof PayCardIndexRoute
  '/payment/failed/': typeof PaymentFailedIndexRoute
  '/payment/paypro-return/': typeof PaymentPayproReturnIndexRoute
  '/payment/success/': typeof PaymentSuccessIndexRoute
  '/purchase/$id/': typeof PurchaseIdIndexRoute
  '/shop/videos/': typeof ShopVideosIndexRoute
  '/checkout/free-fire/$id/': typeof CheckoutFreeFireIdIndexRoute
  '/honor-of-kings/purchase/$id/': typeof HonorOfKingsPurchaseIdIndexRoute
  '/midasbuy/buy/freefire/': typeof MidasbuyBuyFreefireIndexRoute
  '/midasbuy/buy/pubgm/': typeof MidasbuyBuyPubgmIndexRoute
  '/pubg-accounts/checkout/$id/': typeof PubgAccountsCheckoutIdIndexRoute
  '/purchase/free-fire/$id/': typeof PurchaseFreeFireIdIndexRoute
  '/roblox/checkout/$id/': typeof RobloxCheckoutIdIndexRoute
  '/roblox/purchase/$id/': typeof RobloxPurchaseIdIndexRoute
  '/valorant/checkout/$id/': typeof ValorantCheckoutIdIndexRoute
  '/valorant/purchase/$id/': typeof ValorantPurchaseIdIndexRoute
  '/api/auth/callback/google/': typeof ApiAuthCallbackGoogleIndexRoute
  '/midasbuy/$countryCode/buy/bgmi/': typeof MidasbuyCountryCodeBuyBgmiIndexRoute
  '/midasbuy/$countryCode/buy/car/': typeof MidasbuyCountryCodeBuyCarIndexRoute
  '/midasbuy/$countryCode/buy/freefire/': typeof MidasbuyCountryCodeBuyFreefireIndexRoute
  '/midasbuy/$countryCode/buy/honorofkings/': typeof MidasbuyCountryCodeBuyHonorofkingsIndexRoute
  '/midasbuy/$countryCode/buy/pubgm/': typeof MidasbuyCountryCodeBuyPubgmIndexRoute
  '/midasbuy/$countryCode/buy/roblox/': typeof MidasbuyCountryCodeBuyRobloxIndexRoute
  '/midasbuy/$countryCode/buy/valorant/': typeof MidasbuyCountryCodeBuyValorantIndexRoute
  '/midasbuy/$countryCode/game/arenabreakout/': typeof MidasbuyCountryCodeGameArenabreakoutIndexRoute
  '/midasbuy/$countryCode/game/deltaforce/': typeof MidasbuyCountryCodeGameDeltaforceIndexRoute
  '/midasbuy/$countryCode/game/dragonheir/': typeof MidasbuyCountryCodeGameDragonheirIndexRoute
  '/midasbuy/$countryCode/game/honorofkings/': typeof MidasbuyCountryCodeGameHonorofkingsIndexRoute
  '/midasbuy/$countryCode/game/ludo/': typeof MidasbuyCountryCodeGameLudoIndexRoute
  '/midasbuy/$countryCode/game/nba/': typeof MidasbuyCountryCodeGameNbaIndexRoute
  '/midasbuy/$countryCode/game/undawn/': typeof MidasbuyCountryCodeGameUndawnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/payment-success'
    | '/about-midasbuy/'
    | '/admin/'
    | '/auth/'
    | '/bgmi/'
    | '/blogs/'
    | '/car-purchase/'
    | '/careers/'
    | '/contact-us/'
    | '/cookie-policy/'
    | '/copyright-notice/'
    | '/countries/'
    | '/coupons/'
    | '/customer-reviews/'
    | '/dashboard/'
    | '/events/'
    | '/faqs/'
    | '/free-fire/'
    | '/gaming-shop/'
    | '/help-center/'
    | '/honor-of-kings/'
    | '/ip-detector/'
    | '/my-feedbacks/'
    | '/notifications/'
    | '/order-cancelled/'
    | '/order-center/'
    | '/partners/'
    | '/payment-canceled/'
    | '/payment-issues/'
    | '/player-id/'
    | '/press/'
    | '/privacy-policy/'
    | '/profile/'
    | '/pubg-accounts/'
    | '/pubg-mobile/'
    | '/purchase-history/'
    | '/redeem/'
    | '/refund-policy/'
    | '/reset-password/'
    | '/roblox/'
    | '/security/'
    | '/terms-of-service/'
    | '/thank-you/'
    | '/thankyou/'
    | '/track-orders/'
    | '/valorant/'
    | '/auth/callback/'
    | '/blog/$slug/'
    | '/checkout/$id/'
    | '/midasbuy/$countryCode/'
    | '/pay/card/'
    | '/payment/failed/'
    | '/payment/paypro-return/'
    | '/payment/success/'
    | '/purchase/$id/'
    | '/shop/videos/'
    | '/checkout/free-fire/$id/'
    | '/honor-of-kings/purchase/$id/'
    | '/midasbuy/buy/freefire/'
    | '/midasbuy/buy/pubgm/'
    | '/pubg-accounts/checkout/$id/'
    | '/purchase/free-fire/$id/'
    | '/roblox/checkout/$id/'
    | '/roblox/purchase/$id/'
    | '/valorant/checkout/$id/'
    | '/valorant/purchase/$id/'
    | '/api/auth/callback/google/'
    | '/midasbuy/$countryCode/buy/bgmi/'
    | '/midasbuy/$countryCode/buy/car/'
    | '/midasbuy/$countryCode/buy/freefire/'
    | '/midasbuy/$countryCode/buy/honorofkings/'
    | '/midasbuy/$countryCode/buy/pubgm/'
    | '/midasbuy/$countryCode/buy/roblox/'
    | '/midasbuy/$countryCode/buy/valorant/'
    | '/midasbuy/$countryCode/game/arenabreakout/'
    | '/midasbuy/$countryCode/game/deltaforce/'
    | '/midasbuy/$countryCode/game/dragonheir/'
    | '/midasbuy/$countryCode/game/honorofkings/'
    | '/midasbuy/$countryCode/game/ludo/'
    | '/midasbuy/$countryCode/game/nba/'
    | '/midasbuy/$countryCode/game/undawn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/payment-success'
    | '/about-midasbuy'
    | '/admin'
    | '/auth'
    | '/bgmi'
    | '/blogs'
    | '/car-purchase'
    | '/careers'
    | '/contact-us'
    | '/cookie-policy'
    | '/copyright-notice'
    | '/countries'
    | '/coupons'
    | '/customer-reviews'
    | '/dashboard'
    | '/events'
    | '/faqs'
    | '/free-fire'
    | '/gaming-shop'
    | '/help-center'
    | '/honor-of-kings'
    | '/ip-detector'
    | '/my-feedbacks'
    | '/notifications'
    | '/order-cancelled'
    | '/order-center'
    | '/partners'
    | '/payment-canceled'
    | '/payment-issues'
    | '/player-id'
    | '/press'
    | '/privacy-policy'
    | '/profile'
    | '/pubg-accounts'
    | '/pubg-mobile'
    | '/purchase-history'
    | '/redeem'
    | '/refund-policy'
    | '/reset-password'
    | '/roblox'
    | '/security'
    | '/terms-of-service'
    | '/thank-you'
    | '/thankyou'
    | '/track-orders'
    | '/valorant'
    | '/auth/callback'
    | '/blog/$slug'
    | '/checkout/$id'
    | '/midasbuy/$countryCode'
    | '/pay/card'
    | '/payment/failed'
    | '/payment/paypro-return'
    | '/payment/success'
    | '/purchase/$id'
    | '/shop/videos'
    | '/checkout/free-fire/$id'
    | '/honor-of-kings/purchase/$id'
    | '/midasbuy/buy/freefire'
    | '/midasbuy/buy/pubgm'
    | '/pubg-accounts/checkout/$id'
    | '/purchase/free-fire/$id'
    | '/roblox/checkout/$id'
    | '/roblox/purchase/$id'
    | '/valorant/checkout/$id'
    | '/valorant/purchase/$id'
    | '/api/auth/callback/google'
    | '/midasbuy/$countryCode/buy/bgmi'
    | '/midasbuy/$countryCode/buy/car'
    | '/midasbuy/$countryCode/buy/freefire'
    | '/midasbuy/$countryCode/buy/honorofkings'
    | '/midasbuy/$countryCode/buy/pubgm'
    | '/midasbuy/$countryCode/buy/roblox'
    | '/midasbuy/$countryCode/buy/valorant'
    | '/midasbuy/$countryCode/game/arenabreakout'
    | '/midasbuy/$countryCode/game/deltaforce'
    | '/midasbuy/$countryCode/game/dragonheir'
    | '/midasbuy/$countryCode/game/honorofkings'
    | '/midasbuy/$countryCode/game/ludo'
    | '/midasbuy/$countryCode/game/nba'
    | '/midasbuy/$countryCode/game/undawn'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/payment-success'
    | '/about-midasbuy/'
    | '/admin/'
    | '/auth/'
    | '/bgmi/'
    | '/blogs/'
    | '/car-purchase/'
    | '/careers/'
    | '/contact-us/'
    | '/cookie-policy/'
    | '/copyright-notice/'
    | '/countries/'
    | '/coupons/'
    | '/customer-reviews/'
    | '/dashboard/'
    | '/events/'
    | '/faqs/'
    | '/free-fire/'
    | '/gaming-shop/'
    | '/help-center/'
    | '/honor-of-kings/'
    | '/ip-detector/'
    | '/my-feedbacks/'
    | '/notifications/'
    | '/order-cancelled/'
    | '/order-center/'
    | '/partners/'
    | '/payment-canceled/'
    | '/payment-issues/'
    | '/player-id/'
    | '/press/'
    | '/privacy-policy/'
    | '/profile/'
    | '/pubg-accounts/'
    | '/pubg-mobile/'
    | '/purchase-history/'
    | '/redeem/'
    | '/refund-policy/'
    | '/reset-password/'
    | '/roblox/'
    | '/security/'
    | '/terms-of-service/'
    | '/thank-you/'
    | '/thankyou/'
    | '/track-orders/'
    | '/valorant/'
    | '/auth/callback/'
    | '/blog/$slug/'
    | '/checkout/$id/'
    | '/midasbuy/$countryCode/'
    | '/pay/card/'
    | '/payment/failed/'
    | '/payment/paypro-return/'
    | '/payment/success/'
    | '/purchase/$id/'
    | '/shop/videos/'
    | '/checkout/free-fire/$id/'
    | '/honor-of-kings/purchase/$id/'
    | '/midasbuy/buy/freefire/'
    | '/midasbuy/buy/pubgm/'
    | '/pubg-accounts/checkout/$id/'
    | '/purchase/free-fire/$id/'
    | '/roblox/checkout/$id/'
    | '/roblox/purchase/$id/'
    | '/valorant/checkout/$id/'
    | '/valorant/purchase/$id/'
    | '/api/auth/callback/google/'
    | '/midasbuy/$countryCode/buy/bgmi/'
    | '/midasbuy/$countryCode/buy/car/'
    | '/midasbuy/$countryCode/buy/freefire/'
    | '/midasbuy/$countryCode/buy/honorofkings/'
    | '/midasbuy/$countryCode/buy/pubgm/'
    | '/midasbuy/$countryCode/buy/roblox/'
    | '/midasbuy/$countryCode/buy/valorant/'
    | '/midasbuy/$countryCode/game/arenabreakout/'
    | '/midasbuy/$countryCode/game/deltaforce/'
    | '/midasbuy/$countryCode/game/dragonheir/'
    | '/midasbuy/$countryCode/game/honorofkings/'
    | '/midasbuy/$countryCode/game/ludo/'
    | '/midasbuy/$countryCode/game/nba/'
    | '/midasbuy/$countryCode/game/undawn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AboutMidasbuyIndexRoute: typeof AboutMidasbuyIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  BgmiIndexRoute: typeof BgmiIndexRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  CarPurchaseIndexRoute: typeof CarPurchaseIndexRoute
  CareersIndexRoute: typeof CareersIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  CookiePolicyIndexRoute: typeof CookiePolicyIndexRoute
  CopyrightNoticeIndexRoute: typeof CopyrightNoticeIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  CouponsIndexRoute: typeof CouponsIndexRoute
  CustomerReviewsIndexRoute: typeof CustomerReviewsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  FaqsIndexRoute: typeof FaqsIndexRoute
  FreeFireIndexRoute: typeof FreeFireIndexRoute
  GamingShopIndexRoute: typeof GamingShopIndexRoute
  HelpCenterIndexRoute: typeof HelpCenterIndexRoute
  HonorOfKingsIndexRoute: typeof HonorOfKingsIndexRoute
  IpDetectorIndexRoute: typeof IpDetectorIndexRoute
  MyFeedbacksIndexRoute: typeof MyFeedbacksIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  OrderCancelledIndexRoute: typeof OrderCancelledIndexRoute
  OrderCenterIndexRoute: typeof OrderCenterIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  PaymentCanceledIndexRoute: typeof PaymentCanceledIndexRoute
  PaymentIssuesIndexRoute: typeof PaymentIssuesIndexRoute
  PlayerIdIndexRoute: typeof PlayerIdIndexRoute
  PressIndexRoute: typeof PressIndexRoute
  PrivacyPolicyIndexRoute: typeof PrivacyPolicyIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  PubgAccountsIndexRoute: typeof PubgAccountsIndexRoute
  PubgMobileIndexRoute: typeof PubgMobileIndexRoute
  PurchaseHistoryIndexRoute: typeof PurchaseHistoryIndexRoute
  RedeemIndexRoute: typeof RedeemIndexRoute
  RefundPolicyIndexRoute: typeof RefundPolicyIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  RobloxIndexRoute: typeof RobloxIndexRoute
  SecurityIndexRoute: typeof SecurityIndexRoute
  TermsOfServiceIndexRoute: typeof TermsOfServiceIndexRoute
  ThankYouIndexRoute: typeof ThankYouIndexRoute
  ThankyouIndexRoute: typeof ThankyouIndexRoute
  TrackOrdersIndexRoute: typeof TrackOrdersIndexRoute
  ValorantIndexRoute: typeof ValorantIndexRoute
  AuthCallbackIndexRoute: typeof AuthCallbackIndexRoute
  BlogSlugIndexRoute: typeof BlogSlugIndexRoute
  CheckoutIdIndexRoute: typeof CheckoutIdIndexRoute
  MidasbuyCountryCodeIndexRoute: typeof MidasbuyCountryCodeIndexRoute
  PayCardIndexRoute: typeof PayCardIndexRoute
  PaymentFailedIndexRoute: typeof PaymentFailedIndexRoute
  PaymentPayproReturnIndexRoute: typeof PaymentPayproReturnIndexRoute
  PaymentSuccessIndexRoute: typeof PaymentSuccessIndexRoute
  PurchaseIdIndexRoute: typeof PurchaseIdIndexRoute
  ShopVideosIndexRoute: typeof ShopVideosIndexRoute
  CheckoutFreeFireIdIndexRoute: typeof CheckoutFreeFireIdIndexRoute
  HonorOfKingsPurchaseIdIndexRoute: typeof HonorOfKingsPurchaseIdIndexRoute
  MidasbuyBuyFreefireIndexRoute: typeof MidasbuyBuyFreefireIndexRoute
  MidasbuyBuyPubgmIndexRoute: typeof MidasbuyBuyPubgmIndexRoute
  PubgAccountsCheckoutIdIndexRoute: typeof PubgAccountsCheckoutIdIndexRoute
  PurchaseFreeFireIdIndexRoute: typeof PurchaseFreeFireIdIndexRoute
  RobloxCheckoutIdIndexRoute: typeof RobloxCheckoutIdIndexRoute
  RobloxPurchaseIdIndexRoute: typeof RobloxPurchaseIdIndexRoute
  ValorantCheckoutIdIndexRoute: typeof ValorantCheckoutIdIndexRoute
  ValorantPurchaseIdIndexRoute: typeof ValorantPurchaseIdIndexRoute
  ApiAuthCallbackGoogleIndexRoute: typeof ApiAuthCallbackGoogleIndexRoute
  MidasbuyCountryCodeBuyBgmiIndexRoute: typeof MidasbuyCountryCodeBuyBgmiIndexRoute
  MidasbuyCountryCodeBuyCarIndexRoute: typeof MidasbuyCountryCodeBuyCarIndexRoute
  MidasbuyCountryCodeBuyFreefireIndexRoute: typeof MidasbuyCountryCodeBuyFreefireIndexRoute
  MidasbuyCountryCodeBuyHonorofkingsIndexRoute: typeof MidasbuyCountryCodeBuyHonorofkingsIndexRoute
  MidasbuyCountryCodeBuyPubgmIndexRoute: typeof MidasbuyCountryCodeBuyPubgmIndexRoute
  MidasbuyCountryCodeBuyRobloxIndexRoute: typeof MidasbuyCountryCodeBuyRobloxIndexRoute
  MidasbuyCountryCodeBuyValorantIndexRoute: typeof MidasbuyCountryCodeBuyValorantIndexRoute
  MidasbuyCountryCodeGameArenabreakoutIndexRoute: typeof MidasbuyCountryCodeGameArenabreakoutIndexRoute
  MidasbuyCountryCodeGameDeltaforceIndexRoute: typeof MidasbuyCountryCodeGameDeltaforceIndexRoute
  MidasbuyCountryCodeGameDragonheirIndexRoute: typeof MidasbuyCountryCodeGameDragonheirIndexRoute
  MidasbuyCountryCodeGameHonorofkingsIndexRoute: typeof MidasbuyCountryCodeGameHonorofkingsIndexRoute
  MidasbuyCountryCodeGameLudoIndexRoute: typeof MidasbuyCountryCodeGameLudoIndexRoute
  MidasbuyCountryCodeGameNbaIndexRoute: typeof MidasbuyCountryCodeGameNbaIndexRoute
  MidasbuyCountryCodeGameUndawnIndexRoute: typeof MidasbuyCountryCodeGameUndawnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-midasbuy/': {
      id: '/about-midasbuy/'
      path: '/about-midasbuy'
      fullPath: '/about-midasbuy/'
      preLoaderRoute: typeof AboutMidasbuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bgmi/': {
      id: '/bgmi/'
      path: '/bgmi'
      fullPath: '/bgmi/'
      preLoaderRoute: typeof BgmiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-purchase/': {
      id: '/car-purchase/'
      path: '/car-purchase'
      fullPath: '/car-purchase/'
      preLoaderRoute: typeof CarPurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers/': {
      id: '/careers/'
      path: '/careers'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy/': {
      id: '/cookie-policy/'
      path: '/cookie-policy'
      fullPath: '/cookie-policy/'
      preLoaderRoute: typeof CookiePolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copyright-notice/': {
      id: '/copyright-notice/'
      path: '/copyright-notice'
      fullPath: '/copyright-notice/'
      preLoaderRoute: typeof CopyrightNoticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons/': {
      id: '/coupons/'
      path: '/coupons'
      fullPath: '/coupons/'
      preLoaderRoute: typeof CouponsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-reviews/': {
      id: '/customer-reviews/'
      path: '/customer-reviews'
      fullPath: '/customer-reviews/'
      preLoaderRoute: typeof CustomerReviewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs/': {
      id: '/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof FaqsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-fire/': {
      id: '/free-fire/'
      path: '/free-fire'
      fullPath: '/free-fire/'
      preLoaderRoute: typeof FreeFireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming-shop/': {
      id: '/gaming-shop/'
      path: '/gaming-shop'
      fullPath: '/gaming-shop/'
      preLoaderRoute: typeof GamingShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help-center/': {
      id: '/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof HelpCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honor-of-kings/': {
      id: '/honor-of-kings/'
      path: '/honor-of-kings'
      fullPath: '/honor-of-kings/'
      preLoaderRoute: typeof HonorOfKingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-detector/': {
      id: '/ip-detector/'
      path: '/ip-detector'
      fullPath: '/ip-detector/'
      preLoaderRoute: typeof IpDetectorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-feedbacks/': {
      id: '/my-feedbacks/'
      path: '/my-feedbacks'
      fullPath: '/my-feedbacks/'
      preLoaderRoute: typeof MyFeedbacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-cancelled/': {
      id: '/order-cancelled/'
      path: '/order-cancelled'
      fullPath: '/order-cancelled/'
      preLoaderRoute: typeof OrderCancelledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-center/': {
      id: '/order-center/'
      path: '/order-center'
      fullPath: '/order-center/'
      preLoaderRoute: typeof OrderCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-canceled/': {
      id: '/payment-canceled/'
      path: '/payment-canceled'
      fullPath: '/payment-canceled/'
      preLoaderRoute: typeof PaymentCanceledIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-issues/': {
      id: '/payment-issues/'
      path: '/payment-issues'
      fullPath: '/payment-issues/'
      preLoaderRoute: typeof PaymentIssuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-id/': {
      id: '/player-id/'
      path: '/player-id'
      fullPath: '/player-id/'
      preLoaderRoute: typeof PlayerIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press/': {
      id: '/press/'
      path: '/press'
      fullPath: '/press/'
      preLoaderRoute: typeof PressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy/': {
      id: '/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy/'
      preLoaderRoute: typeof PrivacyPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubg-accounts/': {
      id: '/pubg-accounts/'
      path: '/pubg-accounts'
      fullPath: '/pubg-accounts/'
      preLoaderRoute: typeof PubgAccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubg-mobile/': {
      id: '/pubg-mobile/'
      path: '/pubg-mobile'
      fullPath: '/pubg-mobile/'
      preLoaderRoute: typeof PubgMobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-history/': {
      id: '/purchase-history/'
      path: '/purchase-history'
      fullPath: '/purchase-history/'
      preLoaderRoute: typeof PurchaseHistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem/': {
      id: '/redeem/'
      path: '/redeem'
      fullPath: '/redeem/'
      preLoaderRoute: typeof RedeemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy/': {
      id: '/refund-policy/'
      path: '/refund-policy'
      fullPath: '/refund-policy/'
      preLoaderRoute: typeof RefundPolicyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox/': {
      id: '/roblox/'
      path: '/roblox'
      fullPath: '/roblox/'
      preLoaderRoute: typeof RobloxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security/': {
      id: '/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof SecurityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service/': {
      id: '/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/terms-of-service/'
      preLoaderRoute: typeof TermsOfServiceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you/': {
      id: '/thank-you/'
      path: '/thank-you'
      fullPath: '/thank-you/'
      preLoaderRoute: typeof ThankYouIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thankyou/': {
      id: '/thankyou/'
      path: '/thankyou'
      fullPath: '/thankyou/'
      preLoaderRoute: typeof ThankyouIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-orders/': {
      id: '/track-orders/'
      path: '/track-orders'
      fullPath: '/track-orders/'
      preLoaderRoute: typeof TrackOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valorant/': {
      id: '/valorant/'
      path: '/valorant'
      fullPath: '/valorant/'
      preLoaderRoute: typeof ValorantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/': {
      id: '/auth/callback/'
      path: '/auth/callback'
      fullPath: '/auth/callback/'
      preLoaderRoute: typeof AuthCallbackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug/': {
      id: '/blog/$slug/'
      path: '/blog/$slug'
      fullPath: '/blog/$slug/'
      preLoaderRoute: typeof BlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id/': {
      id: '/checkout/$id/'
      path: '/checkout/$id'
      fullPath: '/checkout/$id/'
      preLoaderRoute: typeof CheckoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/': {
      id: '/midasbuy/$countryCode/'
      path: '/midasbuy/$countryCode'
      fullPath: '/midasbuy/$countryCode/'
      preLoaderRoute: typeof MidasbuyCountryCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/card/': {
      id: '/pay/card/'
      path: '/pay/card'
      fullPath: '/pay/card/'
      preLoaderRoute: typeof PayCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed/': {
      id: '/payment/failed/'
      path: '/payment/failed'
      fullPath: '/payment/failed/'
      preLoaderRoute: typeof PaymentFailedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/paypro-return/': {
      id: '/payment/paypro-return/'
      path: '/payment/paypro-return'
      fullPath: '/payment/paypro-return/'
      preLoaderRoute: typeof PaymentPayproReturnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success/': {
      id: '/payment/success/'
      path: '/payment/success'
      fullPath: '/payment/success/'
      preLoaderRoute: typeof PaymentSuccessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$id/': {
      id: '/purchase/$id/'
      path: '/purchase/$id'
      fullPath: '/purchase/$id/'
      preLoaderRoute: typeof PurchaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/videos/': {
      id: '/shop/videos/'
      path: '/shop/videos'
      fullPath: '/shop/videos/'
      preLoaderRoute: typeof ShopVideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/free-fire/$id/': {
      id: '/checkout/free-fire/$id/'
      path: '/checkout/free-fire/$id'
      fullPath: '/checkout/free-fire/$id/'
      preLoaderRoute: typeof CheckoutFreeFireIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honor-of-kings/purchase/$id/': {
      id: '/honor-of-kings/purchase/$id/'
      path: '/honor-of-kings/purchase/$id'
      fullPath: '/honor-of-kings/purchase/$id/'
      preLoaderRoute: typeof HonorOfKingsPurchaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/buy/freefire/': {
      id: '/midasbuy/buy/freefire/'
      path: '/midasbuy/buy/freefire'
      fullPath: '/midasbuy/buy/freefire/'
      preLoaderRoute: typeof MidasbuyBuyFreefireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/buy/pubgm/': {
      id: '/midasbuy/buy/pubgm/'
      path: '/midasbuy/buy/pubgm'
      fullPath: '/midasbuy/buy/pubgm/'
      preLoaderRoute: typeof MidasbuyBuyPubgmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pubg-accounts/checkout/$id/': {
      id: '/pubg-accounts/checkout/$id/'
      path: '/pubg-accounts/checkout/$id'
      fullPath: '/pubg-accounts/checkout/$id/'
      preLoaderRoute: typeof PubgAccountsCheckoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/free-fire/$id/': {
      id: '/purchase/free-fire/$id/'
      path: '/purchase/free-fire/$id'
      fullPath: '/purchase/free-fire/$id/'
      preLoaderRoute: typeof PurchaseFreeFireIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox/checkout/$id/': {
      id: '/roblox/checkout/$id/'
      path: '/roblox/checkout/$id'
      fullPath: '/roblox/checkout/$id/'
      preLoaderRoute: typeof RobloxCheckoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roblox/purchase/$id/': {
      id: '/roblox/purchase/$id/'
      path: '/roblox/purchase/$id'
      fullPath: '/roblox/purchase/$id/'
      preLoaderRoute: typeof RobloxPurchaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valorant/checkout/$id/': {
      id: '/valorant/checkout/$id/'
      path: '/valorant/checkout/$id'
      fullPath: '/valorant/checkout/$id/'
      preLoaderRoute: typeof ValorantCheckoutIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valorant/purchase/$id/': {
      id: '/valorant/purchase/$id/'
      path: '/valorant/purchase/$id'
      fullPath: '/valorant/purchase/$id/'
      preLoaderRoute: typeof ValorantPurchaseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google/': {
      id: '/api/auth/callback/google/'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google/'
      preLoaderRoute: typeof ApiAuthCallbackGoogleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/bgmi/': {
      id: '/midasbuy/$countryCode/buy/bgmi/'
      path: '/midasbuy/$countryCode/buy/bgmi'
      fullPath: '/midasbuy/$countryCode/buy/bgmi/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyBgmiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/car/': {
      id: '/midasbuy/$countryCode/buy/car/'
      path: '/midasbuy/$countryCode/buy/car'
      fullPath: '/midasbuy/$countryCode/buy/car/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyCarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/freefire/': {
      id: '/midasbuy/$countryCode/buy/freefire/'
      path: '/midasbuy/$countryCode/buy/freefire'
      fullPath: '/midasbuy/$countryCode/buy/freefire/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyFreefireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/honorofkings/': {
      id: '/midasbuy/$countryCode/buy/honorofkings/'
      path: '/midasbuy/$countryCode/buy/honorofkings'
      fullPath: '/midasbuy/$countryCode/buy/honorofkings/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyHonorofkingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/pubgm/': {
      id: '/midasbuy/$countryCode/buy/pubgm/'
      path: '/midasbuy/$countryCode/buy/pubgm'
      fullPath: '/midasbuy/$countryCode/buy/pubgm/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyPubgmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/roblox/': {
      id: '/midasbuy/$countryCode/buy/roblox/'
      path: '/midasbuy/$countryCode/buy/roblox'
      fullPath: '/midasbuy/$countryCode/buy/roblox/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyRobloxIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/buy/valorant/': {
      id: '/midasbuy/$countryCode/buy/valorant/'
      path: '/midasbuy/$countryCode/buy/valorant'
      fullPath: '/midasbuy/$countryCode/buy/valorant/'
      preLoaderRoute: typeof MidasbuyCountryCodeBuyValorantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/arenabreakout/': {
      id: '/midasbuy/$countryCode/game/arenabreakout/'
      path: '/midasbuy/$countryCode/game/arenabreakout'
      fullPath: '/midasbuy/$countryCode/game/arenabreakout/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameArenabreakoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/deltaforce/': {
      id: '/midasbuy/$countryCode/game/deltaforce/'
      path: '/midasbuy/$countryCode/game/deltaforce'
      fullPath: '/midasbuy/$countryCode/game/deltaforce/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameDeltaforceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/dragonheir/': {
      id: '/midasbuy/$countryCode/game/dragonheir/'
      path: '/midasbuy/$countryCode/game/dragonheir'
      fullPath: '/midasbuy/$countryCode/game/dragonheir/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameDragonheirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/honorofkings/': {
      id: '/midasbuy/$countryCode/game/honorofkings/'
      path: '/midasbuy/$countryCode/game/honorofkings'
      fullPath: '/midasbuy/$countryCode/game/honorofkings/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameHonorofkingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/ludo/': {
      id: '/midasbuy/$countryCode/game/ludo/'
      path: '/midasbuy/$countryCode/game/ludo'
      fullPath: '/midasbuy/$countryCode/game/ludo/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameLudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/nba/': {
      id: '/midasbuy/$countryCode/game/nba/'
      path: '/midasbuy/$countryCode/game/nba'
      fullPath: '/midasbuy/$countryCode/game/nba/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameNbaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/midasbuy/$countryCode/game/undawn/': {
      id: '/midasbuy/$countryCode/game/undawn/'
      path: '/midasbuy/$countryCode/game/undawn'
      fullPath: '/midasbuy/$countryCode/game/undawn/'
      preLoaderRoute: typeof MidasbuyCountryCodeGameUndawnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AboutMidasbuyIndexRoute: AboutMidasbuyIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  BgmiIndexRoute: BgmiIndexRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  CarPurchaseIndexRoute: CarPurchaseIndexRoute,
  CareersIndexRoute: CareersIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  CookiePolicyIndexRoute: CookiePolicyIndexRoute,
  CopyrightNoticeIndexRoute: CopyrightNoticeIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  CouponsIndexRoute: CouponsIndexRoute,
  CustomerReviewsIndexRoute: CustomerReviewsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  FaqsIndexRoute: FaqsIndexRoute,
  FreeFireIndexRoute: FreeFireIndexRoute,
  GamingShopIndexRoute: GamingShopIndexRoute,
  HelpCenterIndexRoute: HelpCenterIndexRoute,
  HonorOfKingsIndexRoute: HonorOfKingsIndexRoute,
  IpDetectorIndexRoute: IpDetectorIndexRoute,
  MyFeedbacksIndexRoute: MyFeedbacksIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  OrderCancelledIndexRoute: OrderCancelledIndexRoute,
  OrderCenterIndexRoute: OrderCenterIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  PaymentCanceledIndexRoute: PaymentCanceledIndexRoute,
  PaymentIssuesIndexRoute: PaymentIssuesIndexRoute,
  PlayerIdIndexRoute: PlayerIdIndexRoute,
  PressIndexRoute: PressIndexRoute,
  PrivacyPolicyIndexRoute: PrivacyPolicyIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  PubgAccountsIndexRoute: PubgAccountsIndexRoute,
  PubgMobileIndexRoute: PubgMobileIndexRoute,
  PurchaseHistoryIndexRoute: PurchaseHistoryIndexRoute,
  RedeemIndexRoute: RedeemIndexRoute,
  RefundPolicyIndexRoute: RefundPolicyIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  RobloxIndexRoute: RobloxIndexRoute,
  SecurityIndexRoute: SecurityIndexRoute,
  TermsOfServiceIndexRoute: TermsOfServiceIndexRoute,
  ThankYouIndexRoute: ThankYouIndexRoute,
  ThankyouIndexRoute: ThankyouIndexRoute,
  TrackOrdersIndexRoute: TrackOrdersIndexRoute,
  ValorantIndexRoute: ValorantIndexRoute,
  AuthCallbackIndexRoute: AuthCallbackIndexRoute,
  BlogSlugIndexRoute: BlogSlugIndexRoute,
  CheckoutIdIndexRoute: CheckoutIdIndexRoute,
  MidasbuyCountryCodeIndexRoute: MidasbuyCountryCodeIndexRoute,
  PayCardIndexRoute: PayCardIndexRoute,
  PaymentFailedIndexRoute: PaymentFailedIndexRoute,
  PaymentPayproReturnIndexRoute: PaymentPayproReturnIndexRoute,
  PaymentSuccessIndexRoute: PaymentSuccessIndexRoute,
  PurchaseIdIndexRoute: PurchaseIdIndexRoute,
  ShopVideosIndexRoute: ShopVideosIndexRoute,
  CheckoutFreeFireIdIndexRoute: CheckoutFreeFireIdIndexRoute,
  HonorOfKingsPurchaseIdIndexRoute: HonorOfKingsPurchaseIdIndexRoute,
  MidasbuyBuyFreefireIndexRoute: MidasbuyBuyFreefireIndexRoute,
  MidasbuyBuyPubgmIndexRoute: MidasbuyBuyPubgmIndexRoute,
  PubgAccountsCheckoutIdIndexRoute: PubgAccountsCheckoutIdIndexRoute,
  PurchaseFreeFireIdIndexRoute: PurchaseFreeFireIdIndexRoute,
  RobloxCheckoutIdIndexRoute: RobloxCheckoutIdIndexRoute,
  RobloxPurchaseIdIndexRoute: RobloxPurchaseIdIndexRoute,
  ValorantCheckoutIdIndexRoute: ValorantCheckoutIdIndexRoute,
  ValorantPurchaseIdIndexRoute: ValorantPurchaseIdIndexRoute,
  ApiAuthCallbackGoogleIndexRoute: ApiAuthCallbackGoogleIndexRoute,
  MidasbuyCountryCodeBuyBgmiIndexRoute: MidasbuyCountryCodeBuyBgmiIndexRoute,
  MidasbuyCountryCodeBuyCarIndexRoute: MidasbuyCountryCodeBuyCarIndexRoute,
  MidasbuyCountryCodeBuyFreefireIndexRoute:
    MidasbuyCountryCodeBuyFreefireIndexRoute,
  MidasbuyCountryCodeBuyHonorofkingsIndexRoute:
    MidasbuyCountryCodeBuyHonorofkingsIndexRoute,
  MidasbuyCountryCodeBuyPubgmIndexRoute: MidasbuyCountryCodeBuyPubgmIndexRoute,
  MidasbuyCountryCodeBuyRobloxIndexRoute:
    MidasbuyCountryCodeBuyRobloxIndexRoute,
  MidasbuyCountryCodeBuyValorantIndexRoute:
    MidasbuyCountryCodeBuyValorantIndexRoute,
  MidasbuyCountryCodeGameArenabreakoutIndexRoute:
    MidasbuyCountryCodeGameArenabreakoutIndexRoute,
  MidasbuyCountryCodeGameDeltaforceIndexRoute:
    MidasbuyCountryCodeGameDeltaforceIndexRoute,
  MidasbuyCountryCodeGameDragonheirIndexRoute:
    MidasbuyCountryCodeGameDragonheirIndexRoute,
  MidasbuyCountryCodeGameHonorofkingsIndexRoute:
    MidasbuyCountryCodeGameHonorofkingsIndexRoute,
  MidasbuyCountryCodeGameLudoIndexRoute: MidasbuyCountryCodeGameLudoIndexRoute,
  MidasbuyCountryCodeGameNbaIndexRoute: MidasbuyCountryCodeGameNbaIndexRoute,
  MidasbuyCountryCodeGameUndawnIndexRoute:
    MidasbuyCountryCodeGameUndawnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
